### ISSUE TITLE
#include "EventToken.h" error

### ISSUE THREAD

**Issue by 2622594863** [webview/webview_go#21] opened 2023-12-14 04:20 UTC
# github.com/webview/webview_go
In file included from C:/Users/26225/go/pkg/mod/github.com/webview/webview_go@v0.0.0-20230901181450-5a14030a9070/libs/webview/include/webview.h:1132,
                 from webview.cc:1:
C:/Users/26225/go/pkg/mod/github.com/webview/webview_go@v0.0.0-20230901181450-5a14030a9070/libs/mswebview2/include/WebView2.h:978:10: fatal error: EventToken.h: No such file or directory
 #include "EventToken.h"
          ^~~~~~~~~~~~~~
compilation terminated.

go version go1.20.11 windows/amd64
What should I do

**Comment by SteffenL** [comment] 2023-12-14 04:28
I responded to this in your issue #20 so I'll mark this as another duplicate of #8.

**Comment by 2622594863** [comment] 2023-12-14 04:39
> I responded to this in your issue #20 so I'll mark this as another duplicate of #8.

Thank you, I succeeded, the reason is that my gcc version is 8.1, I updated to 13 is OK, thank you for your reply

**Closed** 2023-12-14 04:40 UTC
