### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by 2622594863** [webview/webview_go#20] opened 2023-12-13 06:00 UTC
C:/Users/26225/go/pkg/mod/github.com/webview/webview_go@v0.0.0-20230901181450-5a14030a9070/libs/mswebview2/include/WebView2.h:978:10: fatal error: EventToken.h: No such file or directory
 #include "EventToken.h"
          ^~~~~~~~~~~~~~
compilation terminated.

go1.20.11 windows/amd64

**Comment by SteffenL** [comment] 2023-12-13 06:05
Duplicate of #8.

**Closed by SteffenL** 2023-12-13 06:05 UTC

**Comment by 2622594863** [comment] 2023-12-14 04:26
> ContributorThank you for your reply. It is my first time to use GitHub. What should I download? Please let me know. It would be nice to have a download address.

**Comment by SteffenL** [comment] 2023-12-14 04:31
The links are in #8. Those are simply suggestions so which one to use is up to you. I would personally recommend either WinLibs or MSYS2.

**Comment by SteffenL** [comment] 2023-12-14 04:34
You can also just create your own `EventToken.h` file with the types used by WebView2. The file is in the Windows SDK, but also modern MinGW-w64 distributions.
